product: Trusted Postgres Architect
shortname: tpa
title: Trusted Postgres Architect release notes
description: Release notes for Trusted Postgres Architect and later
columns:
- 0:
  label: "EDB Postgres Distributed"
  key: version-link
- 1:
  label: Release Date
  key: shortdate
intro: |
  The Trusted Postgres Architect documentation describes the latest version of Trusted Postgres Architect 23.
precursor:
- version: 23.34.1
  date:  09 Sep 2024
- version: 23.34.0
  date:  22 Aug 2024
- version: 23.33.0
  date:  24 Jun 2024
- version: 23.32.0
  date:  15 May 2024
- version: 23.31.0
  date:  19 Mar 2024
- version: 23.30.0
  date:  19 Mar 2024
- version: 23.29.0
  date:  15 Feb 2024
- version: 23.28.0
  date:  23 Jan 2024
- version: 23.27.0
  date:  19 Dec 2023
- version: 23.26.0
  date:  30 Nov 2023
- version: 23.25.0
  date:  14 Nov 2023
- version: 23.24.0
  date:  17 Oct 2023
- version: 23.23.0
  date:  21 Sep 2023
- version: 23.22.0
  date:  06 Sep 2023
- version: 23.21.0
  date:  05 Sep 2023
- version: 23.20.0
  date:  01 Aug 2023
- version: 23.19.0
  date:  12 Jul 2023
- version: 23.18.0
  date:  23 May 2023
- version: 23.17.0
  date:  10 May 2023
- version: 23.16.0
  date:  21 Mar 2023
- version: 23.15.0
  date:  15 Mar 2023
- version: 23.14.0
  date:  23 Feb 2023
- version: 23.13.0
  date:  22 Feb 2023
- version: 23.12.0
  date:  21 Feb 2023
- version: 23.11.0
  date:  21 Feb 2023
- version: 23.1-11
  date:  \-
